version: '3.9'

volumes:
  stack_db_data:
  stack_pgadmin_data:

services:

  stack_api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: stack_api_bin
    container_name: stack_api
    env_file:
      - .env
    ports:
      - ${PUBLIC_PORT}:${LISTEN_PORT}
    expose:
      - ${PUBLIC_PORT}
    pid: "host"
    command: air
    volumes:
      - .:/go/src/app
